version: "3.8"

services:
  db:
    build:
      context: ./docker/mysql
    container_name: db 
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      - app-network
    restart: always
    ports:
      - 33306:3306
    privileged: true
    volumes:
      - ./data/db/mysql:/var/lib/mysql:rw
    user: mysql
  
  app:
    build:
      context: ./docker/php
    container_name: app
    depends_on:
      - db
    networks:
      - app-network
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ../:/var/www
  
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    depends_on:
      - app
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    tty: true
    volumes:
        - ../:/var/www
        - ./data/logs/nginx:/var/log/nginx
        - ./docker/nginx/sites-available:/etc/nginx/sites-available

  redis:
    container_name: redis
    build: ./docker/redis
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge